apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpe-textext-pvc
  namespace: filenet
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cpe-textext-pv
  volumeName: cpe-textext-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi