apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-textext-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /home/nfs_share/textext
    server: 172.28.157.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-textext-pv