apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: operator-shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/nfs_share/operator
    server: 172.28.157.3
  persistentVolumeReclaimPolicy: Delete